export const roomList = [
  { label: 'Entryway', value: 'Entryway' },
  { label: 'Family Room', value: 'Family Room' },
  { label: 'Living Room', value: 'Living Room' },
  { label: 'Dining Room', value: 'Dining Room' },
  { label: 'Kitchen', value: 'Kitchen' },
  { label: 'Master Bedroom', value: 'Master Bedroom' },
  { label: 'Bedroom 2', value: 'Bedroom 2' },
  { label: 'Bedroom 3', value: 'Bedroom 3' },
  { label: 'Bedroom 4', value: 'Bedroom 4' },
  { label: 'Bedroom 5', value: 'Bedroom 5' },
  { label: 'Office', value: 'Office' },
  { label: 'Bathroom', value: 'Bathroom' },
  { label: 'Laundry Room', value: 'Laundry Room' },
  { label: 'Garage', value: 'Garage' },
  { label: 'Yard / Patio', value: 'Yard / Patio' },
  { label: 'Musical Instruments', value: 'Musical Instruments' },
  { label: 'Sports and Fitness', value: 'Sports and Fitness' },
  { label: 'Boxes - Packed By Owner', value: 'Boxes - Packed By Owner' },
  { label: 'Boxes - Packed By Company', value: 'Boxes - Packed By Company' },
  { label: 'Basement', value: 'Basement' },
  { label: 'Reception', value: 'Reception' },
  { label: 'Conference Room', value: 'Conference Room' },
  { label: 'Waiting Room', value: 'Waiting Room' },
  { label: 'Break Room', value: 'Break Room' },
  { label: 'Bath Room(s)', value: 'Bath Room(s)' },
]
